In [ ]:
A = np.array(
    [
        [0, 1, 0, 1, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 0],
    ],
    dtype=bool,
)

# order = [5, 1, 2, 3, 4, 0, 6, 7]
# A = A[order][:, order]

In [ ]:
import numpy as np

A = np.array(
    [
        [0, 1, 0, 1, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 0],
    ],
    dtype=bool,
)

resultat = A

for i in range(2, len(A) - 1):
    resultat = resultat | np.linalg.matrix_power(A, i)

print(resultat.astype(int))

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1]]


In [24]:
np.array([[0, 1], [0, 0]], dtype=int)
np.array([[0, 1], [0, 0]], dtype=int)
np.array([[1, 0], [0, 1]], dtype=int)

array([[1, 0],
       [0, 1]])